# Generated by Django 2.0 on 2020-08-14 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productId', models.CharField(default='null', max_length=20)),
                ('userId', models.CharField(default='null', max_length=255)),
                ('profileName', models.CharField(default='null', max_length=255)),
                ('helpfulness', models.CharField(default='null', max_length=10)),
                ('score', models.FloatField(default=0.0)),
                ('time', models.CharField(editable=False, max_length=20)),
                ('summary', models.TextField(default='null')),
                ('text', models.TextField(default='null')),
            ],
        ),
    ]
